### ISSUE TITLE
bug: Contrast issue

### ISSUE THREAD

**Issue by narkhedeshubham** [dacoaster/yattie#14]
# Bug Report

**Platform:**

Widows

**YATTIE version:**

0.5.3

**Current behavior:**
![image](https://user-images.githubusercontent.com/76529337/222420971-b6d1df65-68ba-4049-9269-2de73c452976.png)

**Steps to reproduce:**

File --> App Settings --> Dark Mode

**Comment by dacoaster** [comment]
@narkhedeshubham - Thank you for the report!

This issue popped up due to a rework of our early implementation of dark mode, so it is on my radar.

I actually have a branch from a month or so back where I've fixed most of the dark mode issues, but this ended up getting pushed off due to work on some of the integrations.

I need to find the time to review it and ensure everything is covered, but I will work to get this out in the next release.

**Comment by dacoaster** [comment]
@narkhedeshubham - This should be fixed in [v0.5.4](https://github.com/dacoaster/yattie/releases/tag/v0.5.4). Please check it out.
