### ISSUE TITLE
feat: No need to have Comment type drop-box it can change to a checkbox.

### ISSUE THREAD

**Issue by anakhavviswanathan** [dacoaster/yattie#23]
# Feature Request

**Describe the Feature Request**
When the user starts session-->End session, the user can add a summary in the saving prompt box. default the comment type is **summary**  (disabled drop-down box ) this can change into a **checkbox.**

**Describe Preferred Solution** user can get a checkbox or just a heading 
<img width="409" alt="Screenshot_4" src="https://user-images.githubusercontent.com/92415365/225541975-9d564de6-f62d-436c-8065-54d1cea6b95d.png">

**Comment by dacoaster** [comment]
Thank you for the report @anakhavviswanathan.  This exists as it does because the comment type is usually selectable for any other type of comment except the summary.  But at the end of the test, the summary is a special case.

I'll leave this enhancement request open for a while in case others want to comment, but I am undecided as to whether it makes more sense to leave the box as is or just hide it entirely.  I think either makes sense to me.
