### ISSUE TITLE
feat: Online Documentation need to update according to the new feature.

### ISSUE THREAD

**Issue by anakhavviswanathan** [dacoaster/yattie#25]
# Feature Request

**Describe the Feature Request** Online Documentation need to update according to the new feature. There is many differences from the current documentation from the existing version.

**Describe Preferred Solution** **The online documentation needs to update.** 

<img width="402" alt="Screenshot_7" src="https://user-images.githubusercontent.com/92415365/225588623-b33955e3-538b-40ce-9f75-50e9f737bd5f.png">
<img width="402" alt="Screenshot_6" src="https://user-images.githubusercontent.com/92415365/225588659-d96230bb-ddbe-4134-8e91-eb1728a6225a.png">

**Comment by dacoaster** [comment]
Thank you for the report @anakhavviswanathan.

I am painfully aware of how much work is left to be done on [the docs](https://github.com/yatt-ai/yattie-docs).  I've been trying to find someone to help me with those - especially as the app has been undergoing a lot of change/growth.  If you'd like to put in a PR for changes, they'd be very much appreciated!

Otherwise, this is high on my list beyond fixing items in the app itself.  I am hopeful to get them caught up so they can then be maintained more easily on an ongoing basis.

**Comment by dacoaster** [comment]
I'm going to close this issue though since it is not directly related to the code in this repo.  Any specific issues can be opened on [the docs repo](https://github.com/yatt-ai/yattie-docs), but there is a ton that needs to be done there.
